### ISSUE TITLE
Different behaviors for single files and directories

### ISSUE THREAD

**Issue by sushinoya** [nrgpy/nrgpy#11]
For both rld_local and rwd_local, if a single file is passed as `filename` in the init params, it is converted to txt and saved on disk. This behavior is confusing because as a user, I haven't called `local_obj.convert()` yet. On the other hand, if one passes in a directory instead of a single file through the `rwd_dir` or `rld_dir` init params, this requires calling `.convert()` on the local object for conversion.

**Comment by nrgpy** [comment]
which method makes more sense to you?

should it be that

A.1. if a filename is passed it is processed automatically
A.2. if a directory is passed it is processed automatically

or

B all conversions must require a second step after declaring a conversion object?

**Comment by dave-c-vt** [comment]
closed after waiting for feedback.
