### ISSUE TITLE
Is there a way to get the sensor change date based on configuration change?

### ISSUE THREAD

**Issue by kenneth46k** [nrgpy/nrgpy#14]
I can able to convert RLD files. Now I'm trying to find the sensor change date if configuration changes. Is there any trick to find the same.
I can able to view sensor details in each text file. then I need to run a loop to read each file and try to figure out the change manually.

With concat_txt function, it overwrites the sensor configuration with the latest text file.

Regards
Kenneth

**Comment by dave-c-vt** [comment]
hi kenneth64k, thanks for bringing this up. i have been meaning to add this feature for a while.

v 0.17.8 was just released that will accumulate the sensor changes in the ch_info dataframe.

please give it a try and revert back.

**Comment by kenneth46k** [comment]
Thanks Dave! its working.
