### ISSUE TITLE
Cannot concatenate NRG Cloud exported txt data

### ISSUE THREAD

**Issue by nrgpy** [nrgpy/nrgpy#73]
To reproduce:

1. export two ranges of text data
2. attempt to concatenate
3. note exception in `string_date_check` function (nrgpy.utils.utilities.string_date_check)

file date of Cloud export has "." instead of "-" separating YYYYMMDD

**Comment by dave-c-vt** [comment]
addressed with https://github.com/nrgpy/nrgpy/pull/75
